@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class "Record" {
    - attendanceScore: AttendanceScore
    - participationScore: ParticipationScore
    - submissionScore: SubmissionScore
}

show "Record" attributes

AddressBook *-right-> "1" UniqueStudentList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueStudentList
UniqueTagList -[hidden]down- UniqueStudentList

UniqueTagList -right-> "*" Tag
UniqueStudentList -right-> Student

Student -up-> "*" Tag

Student *--> Name
Student *--> StudentNumber
Student *--> Phone
Student *--> Email
Student *--> Telegram
Student *--> RecordList

RecordList --> "0..13" "Record"
@enduml
