@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniqueStudentList
Class Student
Class Name
Class StudentNumber
Class Email
Class Phone
Class Telegram
Class Tag
Class RecordList
Class "Record" {
    - attendanceScore: AttendanceScore
    - participationScore: ParticipationScore
    - submissionScore: SubmissionScore
}
Class I #FFFFFF
}

show "Record" attributes

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueStudentList
UniqueStudentList --> "~* all" Student
Student *--> Name
Student *--> StudentNumber
Student *--> Email
Student *--> Phone
Student *--> Telegram
Student *--> "*" Tag
Student *--> RecordList

RecordList --> "0..13" "Record"

Student -[hidden]up--> I
UniqueStudentList -[hidden]right-> I

Name -[hidden]right-> StudentNumber
StudentNumber -[hidden]right-> Phone
Phone -[hidden]right-> Email
Email -[hidden]right-> Telegram

ModelManager --> "~* filtered" Student
@enduml
