@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ResultDisplay
Class StudentListPanel
Class StudentCard
Class StatusBarFooter
Class CommandBox
Class ViewPanel
Class RightSidePanel
Class HelpPanel
Class ScoreListPanel
Class ScoreCard
Class RecordDisplay
Class TrendPanel
Class TrendListPanel
Class TrendCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" StudentListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow --> "*" RightSidePanel
RightSidePanel --> "0..1" HelpPanel
RightSidePanel --> "0..1" ViewPanel
RightSidePanel --> "0..1" TrendPanel

StudentListPanel -down-> "*" StudentCard

ViewPanel -down-> "1" ScoreListPanel

ScoreListPanel -down-> "1" StudentCard
ScoreListPanel -down-> "3" ScoreCard
ScoreCard -down-> "1" RecordDisplay

TrendPanel -down-> "1"TrendListPanel
TrendListPanel -down-> "*"TrendCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
StudentListPanel --|> UiPart
StudentCard --|> UiPart
StatusBarFooter --|> UiPart
HelpPanel --|> UiPart
ViewPanel --|> UiPart
ScoreListPanel --|> UiPart
ScoreCard --|> UiPart
TrendPanel --|> UiPart
TrendListPanel --|> UiPart
TrendCard --|> UiPart

StudentCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

StudentListPanel -[hidden]left- RightSidePanel
RightSidePanel -[hidden]left- CommandBox
StudentListPanel -[hidden]left- RightSidePanel
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter
ViewPanel -[hidden]left- HelpPanel

MainWindow -[hidden]-|> UiPart
@enduml
