@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ResultDisplay
Class StudentListPanel
Class StatusBarFooter
Class RightSidePanel
Class HelpPanel
Class TrendPanel
Class ViewPanel
Class CommandBox
Class StudentCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down--> "1" StatusBarFooter
MainWindow *-down--> "1" ResultDisplay
MainWindow *-down--> "1" RightSidePanel
MainWindow *-down-->  "1" CommandBox
MainWindow *-down--> "1" StudentListPanel
MainWindow -left--|> UiPart

RightSidePanel ---> "0..1" HelpPanel
RightSidePanel ---> "0..1" TrendPanel
RightSidePanel ---> "0..1" ViewPanel

StudentListPanel -down-> "*" StudentCard

ResultDisplay ---|> UiPart
CommandBox ---|> UiPart
StudentListPanel ----|> UiPart
StudentCard ---|> UiPart
StatusBarFooter ----|> UiPart
HelpPanel ----|> UiPart
ViewPanel ----|> UiPart
TrendPanel ----|> UiPart

StudentCard ..> Model
UiManager -right-> Logic
MainWindow -right-> Logic

StudentListPanel -[hidden]left- CommandBox
RightSidePanel -[hidden]left- ResultDisplay
StudentListPanel -[hidden]left- RightSidePanel
CommandBox -[hidden]left- RightSidePanel
ResultDisplay -[hidden]left- StatusBarFooter
ViewPanel -[hidden]left- HelpPanel

MainWindow -[hidden]-|> UiPart
@enduml
