@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR


package VP as "ViewPanel"{
Class ViewPanel
Class ScoreListPanel
Class ScoreCard
Class RecordDisplay
}

package Model <<Rectangle>> {
Class Model #FFFFFF
}

Class "{abstract}\nUiPart" as UiPart
Class MainWindow #FFFFFF
Class RightSidePanel #FFFFFF
Class StudentCard
Class StudentListPanel

RightSidePanel --> ViewPanel

ViewPanel -down-> "1" ScoreListPanel
ScoreListPanel -right> "1" StudentCard
ScoreListPanel -down-> "3" ScoreCard
ScoreCard --> "1" RecordDisplay
StudentCard .right> Model

StudentListPanel -down--> "*" StudentCard
MainWindow ---> StudentListPanel

ViewPanel -|> UiPart
ScoreListPanel ---|> UiPart
StudentListPanel ---|> UiPart
ScoreCard ---|> UiPart
StudentCard --down|> UiPart
@enduml
